# Generated by Django 4.0 on 2022-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(default='Initial', max_length=30, verbose_name='status'),
        ),
    ]
