# Generated by Django 4.0 on 2022-11-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(related_query_name='shops', to='app_shop.Item'),
        ),
    ]
