# Generated by Django 4.0 on 2022-11-03 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        ('app_shop', '0002_remove_item_shop_shop_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('added_at', models.DateTimeField(default='2022-11-03 17:05:18')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app_users.customer', verbose_name='customer')),
                ('item', models.ManyToManyField(related_query_name='carts', to='app_shop.Item', verbose_name='item')),
            ],
        ),
    ]
