# Generated by Django 4.0 on 2022-11-03 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_alter_cart_added_at_alter_cart_count_alter_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='added_at'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='carts', to='app_shop.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
